likes_like:
    path:     /like/{iduser}/{idcomment}
    defaults: { _controller: "TalentBundle:Likes:like" }
    methods:  GET

likes_getLikeByCommentUserID:
    path:     /getLikeByCommentUserID/{iduser}/{idcomment}
    defaults: { _controller: "TalentBundle:Likes:getLikeByCommentUserID" }
    methods:  GET

