profil_index:
    path:     /getAll
    defaults: { _controller: "TalentBundle:Profil:index" }
    methods:  GET

profil_relatedToProfile:
    path:     /relatedToProfile/{id}
    defaults: { _controller: "TalentBundle:Profil:relatedToProfile" }
    methods:  GET

profil_delete:
    path:     /delete/{id}
    defaults: { _controller: "TalentBundle:Profil:delete" }
    methods:  DELETE

profil_new:
    path:     /create
    defaults: { _controller: "TalentBundle:Profil:new" }
    methods:  [PUT]

profil_edit:
    path:     /edit
    defaults: { _controller: "TalentBundle:Profil:edit" }
    methods:  [POST]

profil_search:
    path:     /search
    defaults: { _controller: "TalentBundle:Profil:search" }
    methods:  [GET]

profil_by_userID:
    path:     /profilByUSerID/{id}
    defaults: { _controller: "TalentBundle:Profil:profilByUSerID" }
    methods:  [GET]

profil_likes_count:
    path:     /countLikes
    defaults: { _controller: "TalentBundle:Profil:getNumberOfLikesPerProfil" }
    methods:  GET

profil_comments_count:
    path:     /countComments
    defaults: { _controller: "TalentBundle:Profil:getNumberOfCommentPerProfil" }
    methods:  GET

