profil_index:
    path:     /getAll
    defaults: { _controller: "TalentBundle:Profil:index" }
    methods:  GET

profil_relatedToProfile:
    path:     /relatedToProfile/{id}
    defaults: { _controller: "TalentBundle:Profil:relatedToProfile" }
    methods:  GET

profil_delete:
    path:     /delete/{id}
    defaults: { _controller: "TalentBundle:Profil:delete" }
    methods:  DELETE

profil_show:
    path:     /{id}/show
    defaults: { _controller: "TalentBundle:Profil:show" }
    methods:  GET

profil_new:
    path:     /create
    defaults: { _controller: "TalentBundle:Profil:new" }
    methods:  [PUT]

profil_edit:
    path:     /edit
    defaults: { _controller: "TalentBundle:Profil:edit" }
    methods:  [POST]


