rating_index:
    path:     /getAll
    defaults: { _controller: "TalentBundle:Rating:index" }
    methods:  GET

rating_show:
    path:     /getByProfilId/{id}
    defaults: { _controller: "TalentBundle:Rating:getByProfilId" }
    methods:  GET

rating_by_user_profil_show:
    path:     /getByProfilUserId/{idProfil}/{idUser}
    defaults: { _controller: "TalentBundle:Rating:getByProfilUserId" }
    methods:  GET

rating_new:
    path:     /rate
    defaults: { _controller: "TalentBundle:Rating:new" }
    methods:  [PUT]

rating_edit:
    path:     /edit
    defaults: { _controller: "TalentBundle:Rating:edit" }
    methods:  [POST]

rating_delete:
    path:     /delete/{id}
    defaults: { _controller: "TalentBundle:Rating:delete" }
    methods:  DELETE
