user_login:
  path:     /loginUser
  defaults: { _controller: "TalentBundle:User:login" }
  methods:  [POST]

user_logout:
  path:     /logoutUser
  defaults: { _controller: "TalentBundle:User:logout" }
  methods:  [POST]
