categoryevent_index:
    path:     /
    defaults: { _controller: "EventBundle:CategoryEvent:index" }
    methods:  GET

categoryevent_show:
    path:     /show/{id}
    defaults: { _controller: "EventBundle:CategoryEvent:show" }
    methods:  GET

categoryevent_new:
    path:     /new
    defaults: { _controller: "EventBundle:CategoryEvent:new" }
    methods:  [GET, POST]

categoryevent_edit:
    path:     /edit
    defaults: { _controller: "EventBundle:CategoryEvent:edit" }
    methods:  [GET, POST]

categoryevent_delete:
    path:     /delete/{id}
    defaults: { _controller: "EventBundle:CategoryEvent:delete" }
    methods:  DELETE
