evenement_index:
    path:     /getAll
    defaults: { _controller: "EventBundle:Evenement:index" }
    methods:  GET

evenement_show:
    path:     /getById/{id}
    defaults: { _controller: "EventBundle:Evenement:show" }
    methods:  GET

evenement_new:
    path:     /create
    defaults: { _controller: "EventBundle:Evenement:new" }
    methods:  [GET, POST]

evenement_edit:
    path:     /edit/{id}
    defaults: { _controller: "EventBundle:Evenement:edit" }
    methods:  [GET, POST]

evenement_delete:
    path:     /delete/{id}
    defaults: { _controller: "EventBundle:Evenement:delete" }
    methods:  DELETE
evenement_participer:
    path:     /participer/{id}
    defaults: { _controller: "EventBundle:Evenement:participer" }
    methods:  GET