talent_profil:
  resource: "@TalentBundle/Resources/config/routing/profil.yml"
  prefix:   /profil
talent_rating:
  resource: "@TalentBundle/Resources/config/routing/rating.yml"
  prefix:   /rating
talent_comment:
  resource: "@TalentBundle/Resources/config/routing/comment.yml"
  prefix:   /comment
talent_likes:
  resource: "@TalentBundle/Resources/config/routing/likes.yml"
  prefix:   /likes