sponsoring:
    resource: "@SponsoringBundle/Resources/config/routing.yml"
    prefix:   /tgt/sponsoring

competition:
    resource: "@CompetitionBundle/Resources/config/routing.yml"
    prefix:   /tgt/competition

forum_c:
    prefix: /tgt/
    resource: "@ForumBundle/Resources/config/routing.yml"

talent:
    resource: "@TalentBundle/Resources/config/routing.yml"
    prefix:   /tgt/talent

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /tgt

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
