<?php

namespace EventBundle\Repository;

/**
 * CategoryEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryEventRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCat($strg)
    {
        $req = $this->createQueryBuilder('m')
            ->where("UPPER(m.titreCat) LIKE UPPER(:tt)")
            ->setParameter('tt', $strg)
            ->getQuery();
        return $req->getResult();
    }
}
