<?php

namespace EventBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends EntityRepository
{
    public function findByTitre($strg)
    {
        $req = $this->createQueryBuilder('m')
            ->where("m.titre LIKE :tt")
            ->setParameter('tt', $strg)
            ->getQuery();
        return $req->getResult();
    }


}
