<?php

namespace EventBundle\Repository;

/**
 * RatingEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingEventRepository extends \Doctrine\ORM\EntityRepository
{
}
