services:
  forum.repository:
    abstract: true
    factory: ['@doctrine.orm.entity_manager', getRepository]
    calls:
      - [setLogger, ['@?logger']]

  forum.article_repository:
    class: ForumBundle\Repository\ArticleRepository
    parent: forum.repository
    arguments: ['ForumBundle:Article']
    lazy: true