<?php

namespace SponsoringBundle\Repository;

/**
 * EntrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrepriseRepository extends \Doctrine\ORM\EntityRepository
{
    public function search_by_nom($nom){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e
                FROM SponsoringBundle:Entreprise e
                WHERE e.nom LIKE :str'
            )
            ->setParameter('str', '%'.$nom.'%')
            ->getResult();
    }

}
