<?php

namespace SponsoringBundle\Repository;

/**
 * SponsoriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SponsoriseRepository extends \Doctrine\ORM\EntityRepository
{

    public function sort_by_Date(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s
                FROM SponsoringBundle:Sponsorise s
                ORDER BY s.dateSp'
            )
            ->getResult();
    }

}
