event_evenement:
    resource: "@EventBundle/Resources/config/routing/evenement.yml"
    prefix:   /event
participer_evenement:
    resource: "@EventBundle/Resources/config/routing/participer.yml"
    prefix:   /participer
favoris_evenement:
    resource: "@EventBundle/Resources/config/routing/favoris.yml"
    prefix:   /favoris
rating_evenement:
    resource: "@EventBundle/Resources/config/routing/ratingEvent.yml"
    prefix:   /ratingEvent
event_homepage:
    path:     /
    defaults: { _controller: EventBundle:Default:index }
