<?php

namespace CompetitionBundle\Repository;

/**
 * CompetitionParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetitionParticipationRepository extends \Doctrine\ORM\EntityRepository
{
}
