<?php

namespace CompetitionBundle\Repository;

/**
 * CompetitionRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetitionRatingRepository extends \Doctrine\ORM\EntityRepository
{
}
